export enum SellerRequestType {
  TEST_DRIVE = 'TEST_DRIVE',
  HOLD_FOR_ONE_DAY = 'HOLD_FOR_ONE_DAY',
  VEHICLE_AVAILABILITY = 'VEHICLE_AVAILABILITY',
  VEHICLE_HISTORY = 'VEHICLE_HISTORY',
  GENERAL = 'GENERAL',
}