export enum PaymentTransferStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT_PROOF_UPLOADED = 'PAYMENT_PROOF_UPLOADED',
  PAYMENT_VERIFIED = 'PAYMENT_VERIFIED',
  OWNERSHIP_TRANSFER_IN_PROGRESS = 'OWNERSHIP_TRANSFER_IN_PROGRESS',
  OWNERSHIP_TRANSFER_COMPLETED = 'OWNERSHIP_TRANSFER_COMPLETED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}